### ISSUE TITLE
reduce prometheus memory usage

### ISSUE THREAD

**Issue by nohant** [sighupio/fury-kubernetes-monitoring#107]
we spent some day working on a prometheus installation and we found that we "leave" too many labels for the metrics, some are even duplicates.

**Proposal**
by adding the following configuration we can remove some of the label which have high cardinality and aren't used in dashboards or rules from the various `FURY modules`
```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  labels:
    prometheus: k8s
  name: k8s
spec:
  writeRelabelConfigs:
    - job_name: id-label
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: 'id'
          action: drop
    - job_name: container_id-label
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: 'container_id'
          action: drop
    - job_name: le-label
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: 'le'
          action: drop
    - job_name: service-name-label
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: 'service-name'
          action: drop
    - job_name: address-label
        metric_relabel_configs:
        - source_labels: [__name__]
          regex: 'address'
          action: drop
```
In order to further save memory it will be a good idea to choose between the `service` and `job` label, since those two are replicated but somewhere its used job, somewhere else is used service.
By choosing which one to use everywhere we can drastically reduce the cardinality by removing the other as per the example posted before.

What do you think about this?
