### ISSUE TITLE
Alertmanager adds namespace to its configuration

### ISSUE THREAD

**Issue by sbruzzese902** [sighupio/fury-kubernetes-monitoring#132]
Hello guys! During a KFD upgrade, I noticed this weird behavior using the current [AlertManagerConfig resources](https://github.com/sighupio/fury-kubernetes-monitoring/blob/main/katalog/alertmanager-operated/alertmanagerconfig.yml).

Inspecting the `/etc/alertmanager/config/alertmanager.yaml` inside alertmanager pods I get this:
```
route:
  routes:
  - receiver: monitoring/deadmanswitch/healthchecks
    matchers:
    - alertname="DeadMansSwitch"
    - namespace="monitoring"
    continue: true
  - receiver: monitoring/infra/infra
    group_by:
    - alertname
    matchers:
    - namespace=~"calico-api|calico-system|cert-manager|gatekeeper-system|ingress-nginx|kube-system|logging|monitoring|pomerium|tigera-operator|vmware-system-csi"
    - alertname=~"TargetDown|KubePersistentVolumeFillingUp|NginxIngressCertificateExpiration|NginxIngressLatencyTooHigh|NginxIngressFailedReload|NginxIngressFailureRate|NginxIngressDown"
    - namespace="monitoring"
    continue: true
  - receiver: monitoring/k8s/k8s
    group_by:
    - alertname
    matchers:
    - alertname=~"NodeNetworkInterfaceFlapping|NodeClockSkewDetected|KubeAPIDown|KubeletDown|KubeletTooManyPods|KubeNodeNotReady|KubeClientCertificateExpiration|NodeFileDescriptorLimit|NodeFilesystemAlmostOutOfFiles|NodeFilesystemAlmostOutOfSpace|NodeFilesystemFilesFillingUp|NodeFilesystemSpaceFillingUp|NodeRAIDDegraded|NodeRAIDDiskFailure|etcdInsufficientMembers|etcdMembersDown|etcdNoLeader|CoreDNSPanic|CoreDNSHealthRequestsLatency|KubeControllerManagerDown|KubeSchedulerDown|PrometheusRuleFailures|AlertmanagerClusterDown|AlertmanagerConfigInconsistent|AlertmanagerFailedReload|X509CertificateExpiration|X509CertificateRenewal"
    - namespace="monitoring"
    continue: true
```

As you can see, alertmanager adds a `namespace = monitoring` label, so the result is that I don't get the alerts delivered correctly to the target URL, because they don't have that label set.

My solution, for now, is to add the `spec.enforcedNamespaceLabel = "namespace"` in Prometheus resource, so every alert generated by Prometheus is injected with a label `namespace = <namespace>`.

However, this solves only the DeadMansSwitch issue, at the moment I'm not sure if the other alert groups are working fine. I will give you more details whenever possible.
